# Generated by Django 3.0.7 on 2020-06-25 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Prices',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('updatedAt', models.CharField(max_length=30)),
                ('high', models.CharField(max_length=30)),
                ('low', models.CharField(max_length=30)),
            ],
        ),
    ]
